version: '2'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:7.1
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public public/index.php
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs

    mysql:
          image: mariadb:10.2
          ports:
            - "3306:3306"
          environment:
            MYSQL_ROOT_PASSWORD: secret
          volumes:
            - cache/db:/var/lib/mysql

    redis:
          image: redis:3.0
          ports:
            - "6379:6379"